services:

  postgres:
    image: postgres:15
    container_name: mlflow_postgres
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: mlflow_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    volumes:
      - ./minio_data:/data

  create_bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minio minio123;
      mc mb myminio/mlflow;
      mc policy set public myminio/mlflow;
      exit 0;
      "

  mlflow:
    image: python:3.11-slim
    container_name: mlflow_server
    depends_on:
      - postgres
      - minio
      - create_bucket
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY_ID: minio123
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: >
      bash -c "
      pip install mlflow psycopg2-binary boto3 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --allowed-hosts 'mlflow:5000,localhost:*,127.0.0.1:*'
      --backend-store-uri postgresql://mlflow:mlflow@postgres:5432/mlflow
      --default-artifact-root s3://mlflow
      "

  # --- SUA API DE CRÉDITO ---
  credit_api:
    build:
      context: ./prod
      dockerfile: Dockerfile
    container_name: credit_scoring_api
    depends_on:
      - mlflow
      - minio
    ports:
      - "8000:8000"
    environment:
      # Importante: Usamos os nomes dos serviços do Docker Compose como hosts
      MLFLOW_TRACKING_URI: http://mlflow:5000
      # Usa versão registrada existente no MLflow
      MLFLOW_MODEL_URI: models:/credit_risk_forecast_v2/1
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio123
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_IGNORE_TLS: "true"
      # Passamos o RUN_ID como variável de ambiente para ser dinâmico
      RUN_ID: "0a718264325d414898f9b5c4c298e272"